#!/bin/bash

# https://stackoverflow.com/a/246128/4804196
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_DIR"/../include/base

app="$top"/apps/app-httpreply

source "$SCRIPT_DIR"/../include/common_functions

setup_app()
{
    git clone https://github.com/unikraft/app-httpreply "$app"

    # Don't do anything else. The default configuration should work.
}

run()
{
    _setup_networking
    pushd "$app" > /dev/null
    export UK_WORKDIR=$(pwd)/../../
    kraft run -b virbr0 "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0 --"
    popd > /dev/null
}

run_qemu()
{
    _setup_networking
    pushd "$app" > /dev/null
    sudo qemu-system-x86_64 \
        -kernel "build/httpreply_kvm-x86_64" \
        -cpu host \
        -enable-kvm \
        -nographic \
        -netdev bridge,id=en0,br=virbr0 \
        -device virtio-net-pci,netdev=en0 \
        -append "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0 --"
    popd > /dev/null
}

source "$SCRIPT_DIR"/../include/common_command
