#!/bin/bash

# https://stackoverflow.com/a/246128/4804196
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_DIR"/../include/base

app="$top"/apps/app-helloworld

source "$SCRIPT_DIR"/../include/common_functions

USE_LWIP=1

setup_app()
{
    if ! test -d "$app"; then
        git clone https://github.com/unikraft/app-helloworld "$app"
    fi

    pushd "$app" > /dev/null

    git reset --hard HEAD

    # Use updated kraft.yaml (including Musl dependency).
    git remote add upb https://github.com/unikraft-upb/app-helloworld
    git fetch upb
    if test "$USE_LWIP" -eq 1; then
        git checkout -b use-lwip-libsodium upb/use-lwip-libsodium
    else
        git checkout -b use-musl-libsodium upb/use-musl-libsodium
    fi

    popd > /dev/null
}

run()
{
    if test ! -d "$app"; then
        echo "$app folder doesn't exist. Did you run '$0 setup'?" 1>&2
        exit 1
    fi
    pushd "$app" > /dev/null
    export UK_WORKDIR=$(pwd)/../../
    kraft run
    popd > /dev/null
}

run_qemu()
{
    #_setup_networking
    if test ! -d "$app"; then
        echo "$app folder doesn't exist. Did you run '$0 setup'?" 1>&2
        exit 1
    fi
    pushd "$app" > /dev/null
    sudo qemu-system-x86_64 \
        -kernel "build/helloworld_kvm-x86_64" \
        -cpu host \
        -enable-kvm \
        -nographic
    popd > /dev/null
}

source "$SCRIPT_DIR"/../include/common_command
