#!/bin/bash

# https://stackoverflow.com/a/246128/4804196
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_DIR"/../include/base

app="$top"/apps/app-micropython

source "$SCRIPT_DIR"/../include/common_functions

USE_LWIP=1

setup_app()
{
    git clone https://github.com/unikraft/app-micropython "$app"

    pushd "$app" > /dev/null

    # Use updated kraft.yaml (including Musl dependency).
    git remote add upb https://github.com/unikraft-upb/app-micropython
    git fetch upb
    git checkout -b use-musl upb/use-musl

    popd > /dev/null
}

run()
{
    pushd "$app" > /dev/null
    export UK_WORKDIR=$(pwd)/../../
    kraft run -M 1024 -i "helloworld.py"
    popd > /dev/null
}

run_qemu()
{
    #_setup_networking
    pushd "$app" > /dev/null
    sudo qemu-system-x86_64 \
        -initrd "helloworld.py" \
        -kernel "build/micropython_kvm-x86_64" \
        -cpu host \
        -enable-kvm \
        -nographic
    popd > /dev/null
}

source "$SCRIPT_DIR"/../include/common_command
