#!/bin/bash

# https://stackoverflow.com/a/246128/4804196
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_DIR"/../include/base

app="$top"/apps/test

source "$SCRIPT_DIR"/../include/common_functions

USE_LWIP=1

setup_app()
{
    if ! test -d "$app"; then
        git clone https://github.com/dragosargint/test "$app"
    fi

    pushd "$app" > /dev/null
    git reset --hard HEAD
    popd > /dev/null

    pushd "$top"/libs > /dev/null
    ln -sfn musl lib-musl
    popd > /dev/null
}

build()
{
    if test ! -d "$app"; then
        echo "$app folder doesn't exist. Did you run '$0 setup'?" 1>&2
        exit 1
    fi
    pushd "$app" > /dev/null
    cp CONFIG_TO_BE_COPIED .config
    make prepare
    make -j $(nproc)
    popd > /dev/null
}

run()
{
    #_setup_networking
    if test ! -d "$app"; then
        echo "$app folder doesn't exist. Did you run '$0 setup'?" 1>&2
        exit 1
    fi
    pushd "$app" > /dev/null
    sudo qemu-system-x86_64 \
        -kernel "build/test_kvm-x86_64" \
        -cpu host \
        -enable-kvm \
        -nographic
    popd > /dev/null
}

source "$SCRIPT_DIR"/../include/common_command
