#!/bin/bash

usage()
{
    echo "Usage: $0 <command>" 1>&2
    echo "  command: setup configure build docker_build clean docker_clean run run_debug remove" 1>&2
}

if test $# -ne 1; then
    usage
    exit 1
fi

command="$1"

case "$command" in

    "setup")
        setup_base
        setup_app
        ;;

    "configure")
        configure
        ;;

    "build")
        build
        ;;

    "docker_build")
        docker_build
        ;;

    "clean")
        clean
        ;;

    "docker_clean")
        docker_clean
        ;;

    "run")
        run
        ;;

    "run_debug")
        run_debug
        ;;

    "remove")
        remove
        ;;

    *)
        echo "Unknown command: $command"
        usage
        exit 1
esac
