#!/bin/bash

need_x86_uktest=1

setup_unikraft()
{
    # Use Simon's scheduling branch.
    #git remote add skuenzer https://github.com/skuenzer/unikraft
    #git fetch skuenzer
    #git checkout -b skuenzer/sched-refactor skuenzer/skuenzer/sched-refactor

    ## Integrate PR #454: lib/uktime: Solve redefining conflicts
    #git remote add dragosargint https://github.com/dragosargint/unikraft
    #git fetch dragosargint
    #git checkout -b uktime dragosargint/uktime

    ## Rebase the two branches.
    #git checkout -b musl-support staging
    #git rebase uktime
    #git rebase skuenzer/sched-refactor

    # Use a merging of Simon's and Dragos's changes.
    git remote add upb https://github.com/unikraft-upb/unikraft
    git fetch upb
    git checkout -b musl-support upb/musl-support
    git checkout -b statfs_to_statvfs-in-macro-guard upb/statfs_to_statvfs-in-macro-guard
    git checkout -b send-recv-guard upb/send-recv-guard
    git checkout -b musl-lwip-compatible upb/musl-lwip-compatible

    # Integrate PRs 553 and 602.
    git remote add maniatro111 https://github.com/maniatro111/unikraft/
    git fetch maniatro111
    git checkout -b clone-rule maniatro111/clone-rule
    git checkout -b disable-uktest-test-myself-suite-when-option-is-disabled maniatro111/disable-uktest-test-myself-suite-when-option-is-disabled

    # Integrate PR 551: Warning fix: uninitialized variable #551
    git remote add mariamosn https://github.com/mariamosn/unikraft/
    git fetch mariamosn
    git checkout -b local2 mariamosn/local2

    # Integrate PRs 638, 639
    git remote add eduardvintila https://github.com/eduardvintila/unikraft/
    git fetch eduardvintila
    git checkout -b fix_open_call eduardvintila/fix_open_call
    git checkout -b fix_pipe_call eduardvintila/fix_pipe_call
    git checkout -b fix_9pfs_rw eduardvintila/fix_9pfs_rw

    # Integrate PRs 636
    git remote add mariasfiraiala https://github.com/mariasfiraiala/unikraft
    git fetch mariasfiraiala
    git checkout -b replace-access-call mariasfiraiala/replace-access-call
    git checkout -b update-legacy_syscall.h mariasfiraiala/update-legacy_syscall.h

    if test ! "$need_x86_uktest" -eq 1; then
        # Integrate PR 606, fixing ARM runs.
        git remote add alexhoppus https://github.com/alexhoppus/unikraft/
        git fetch alexhoppus
        git checkout -b bugfix/uktest_perm_ro alexhoppus/bugfix/uktest_perm_ro
    fi

    git checkout staging
    git rebase musl-support
    git rebase statfs_to_statvfs-in-macro-guard
    git rebase send-recv-guard
    git rebase clone-rule
    git cherry-pick disable-uktest-test-myself-suite-when-option-is-disabled
    git cherry-pick bugfix/uktest_perm_ro
    git cherry-pick local2
    git cherry-pick fix_open_call
    git cherry-pick fix_pipe_call
    git cherry-pick fix_9pfs_rw
    git cherry-pick replace-access-call~1
    git cherry-pick replace-access-call
    git cherry-pick update-legacy_syscall.h
    git cherry-pick musl-lwip-compatible
}

setup_musl()
{
    # Integrate PR #9: Thread support for musl
    git remote add dragosargint https://github.com/dragosargint/lib-musl/
    git fetch dragosargint
    git checkout -b thread_support dragosargint/thread_support

    # Integrate aarch64 PRs: #6, #7, #11, #13
    git remote add kubanrob https://github.com/kubanrob/lib-musl/
    git fetch kubanrob
    git checkout -b add-patches-for-aarch64 kubanrob/add-patches-for-aarch64
    git checkout -b update-aarch64-makefiles kubanrob/update-aarch64-makefiles
    git checkout -b patch-CVE-2020-28928 kubanrob/patch-CVE-2020-28928
    git checkout -b hide-internal-headers kubanrob/hide-internal-headers

    # Integrate build PRs: #15, #17
    git checkout -b parallel-make kubanrob/parallel-make
    git checkout -b dont_clean_includes kubanrob/dont_clean_includes

    # Integrate PR #14:  Enable FPSIMD support on ARM64
    git remote add razvanvirtan https://github.com/razvanvirtan/lib-musl/
    git fetch razvanvirtan
    git checkout -b enable_fpsimd razvanvirtan/enable_fpsimd

    # Integrate PR #12: Add syscall wrapper for getrandom
    git remote add michpappas https://github.com/michpappas/lib-musl/
    git fetch michpappas
    git checkout -b add_syscall_wrapper_for_getrandom michpappas/add_syscall_wrapper_for_getrandom

    # Integrate PRs #18: Always include the uname sources
    git remote add StefanJum https://github.com/StefanJum/lib-musl/
    git fetch StefanJum
    git checkout -b fix-posix-sysinfo StefanJum/fix-posix-sysinfo

    # Integrate PR #19, #20, #22, #23
    git remote add upb https://github.com/unikraft-upb/lib-musl/
    git fetch upb
    git checkout -b makefile-lwip-integration upb/makefile-lwip-integration
    git checkout -b posix-user-sources upb/posix-user-sources
    git checkout -b add-sysexits.h upb/add-sysexits.h
    git checkout -b add-wait.c upb/add-wait.c

    # Rebase all branches
    git checkout -b musl-support staging
    git rebase thread_support
    git cherry-pick add-patches-for-aarch64~3
    git cherry-pick add-patches-for-aarch64~2
    git cherry-pick add-patches-for-aarch64~1
    git cherry-pick add-patches-for-aarch64
    git cherry-pick update-aarch64-makefiles~2
    git cherry-pick update-aarch64-makefiles~1
    git cherry-pick update-aarch64-makefiles
    git cherry-pick patch-CVE-2020-28928
    git cherry-pick add_syscall_wrapper_for_getrandom
    git cherry-pick hide-internal-headers
    git cherry-pick parallel-make
    git cherry-pick enable_fpsimd
    git rebase dont_clean_includes
    git cherry-pick fix-posix-sysinfo
    git cherry-pick makefile-lwip-integration~2
    git cherry-pick makefile-lwip-integration~1
    git cherry-pick makefile-lwip-integration
    git cherry-pick posix-user-sources
    git cherry-pick add-sysexits.h
    git cherry-pick add-wait.c
}

setup_lwip()
{
    # Integrate PR #19: Adopt to refactored scheduling API (lib/uksched)
    git remote add skuenzer https://github.com/skuenzer/lib-lwip
    git fetch skuenzer
    git checkout -b skuenzer/sched-refactor skuenzer/skuenzer/sched-refactor

    # Integrate PR #22: Add uk/essentials.h as include dependency
    git remote add upb https://github.com/unikraft-upb/lib-lwip
    git fetch upb
    git checkout -b fix-__unused upb/fix-__unused

    # Integrate PR #23, #25: Add Musl support
    git remote add upb https://github.com/unikraft-upb/lib-lwip
    git fetch upb
    git checkout -b musl-support upb/musl-support
    git checkout -b remove_ip6addr upb/remove_ip6addr

    # Rebase all branches
    git checkout staging
    git rebase skuenzer/sched-refactor
    git rebase fix-__unused
    git cherry-pick musl-support~2
    git cherry-pick musl-support~1
    git cherry-pick musl-support
    git rebase remove_ip6addr
}

setup_libcxx()
{
    # Integrate PRs #9, #10, #14, #17, #18, #22.
    git remote add upb https://github.com/unikraft-upb/lib-libcxx
    git fetch upb
    git checkout -b fix-features upb/fix-features
    git checkout -b fix-xlocale upb/fix-xlocale
    git checkout -b patch-locale upb/patch-locale
    git checkout -b fix-glue upb/fix-glue
    git checkout -b change-include-next upb/change-include-next
    git checkout -b add-math-header upb/add-math-header

    # Rebase all branches.
    git checkout staging
    git rebase fix-features
    git rebase fix-xlocale
    git rebase patch-locale
    git rebase fix-glue
    git rebase change-include-next
    git rebase add-math-header
}

setup_libcxxabi()
{
    # Integrate PR #2: Config.uk: Fix dependencies with libunwind
    git remote add upb https://github.com/unikraft-upb/lib-libcxxabi
    git fetch upb
    git checkout -b fix-libunwind-dep upb/fix-libunwind-dep

    git checkout staging
    git rebase fix-libunwind-dep
}

setup_libunwind()
{
    # Integrate PR #3: Config.uk: Fix dependencies with libcxxabi
    git remote add upb https://github.com/unikraft-upb/lib-libunwind
    git fetch upb
    git checkout -b fix-libcxxabi-dep upb/fix-libcxxabi-dep

    git checkout staging
    git rebase fix-libcxxabi-dep
}

setup_compiler_rt()
{
    # Integrate PR #8: Circular dependencies if adding libunwind as dependency
    git remote add DeliaPavel https://github.com/DeliaPavel/lib-compiler-rt
    git fetch DeliaPavel
    git checkout -b DeliaPavel-staging DeliaPavel/staging

    git checkout staging
    git rebase DeliaPavel-staging
}

setup_libc_test()
{
    # Integrate PR #1:  Introduce liblibctest for Unikraft
    git remote add maniatro111 https://github.com/maniatro111/lib-libctest
    git fetch maniatro111
    git checkout -b maniatro111-staging maniatro111/staging

    git checkout staging
    git rebase maniatro111-staging
}

setup_libsodium()
{
    # Integrate PR #6: Add the internal 'posix-event' library as a dependency
    git remote add hchandad https://github.com/hchandad/unikraft-libsodium-port/
    git fetch hchandad
    git checkout -b add-posix-event hchandad/add-posix-event

    git checkout staging
    git rebase add-posix-event
}

setup_zlib()
{
    # Integrate PR #4: Update version: 1.2.12 -> 1.2.13
    git remote add Sabanic-P https://github.com/Sabanic-P/lib-zlib
    git fetch Sabanic-P
    git checkout -b changeto.13 Sabanic-P/changeto.13

    git checkout staging
    git rebase changeto.13
}

setup_libuuid()
{
    # Integrate PR #2: Add include/private to the list of include directories
    git remote add upb https://github.com/unikraft-upb/lib-libuuid
    git fetch upb
    git checkout -b include-private upb/include-private

    git checkout staging
    git rebase include-private
}

setup_python3()
{
    # Integrate PR #5: Add patch to disable SOCK_CLOEXEC usage.
    git remote add vladandrew https://github.com/vladandrew/lib-python3
    git fetch vladandrew
    git checkout -b vladb/sock_cloexec vladandrew/vladb/sock_cloexec

    # Integrate PR #9: Use value 8 for SIZEOF_PTHREAD_T
    git remote add upb https://github.com/unikraft-upb/lib-python3
    git fetch upb
    git checkout -b fix_sizeof_pthread_t upb/fix_sizeof_pthread_t

    git checkout staging
    git rebase vladb/sock_cloexec
    git rebase fix_sizeof_pthread_t
}

setup_nginx()
{
    # Integrate PRs #9, #10
    git remote add upb https://github.com/unikraft-upb/lib-nginx
    git fetch upb
    git checkout -b add-posix-lib-dependency upb/add-posix-lib-dependency
    git checkout -b remove-werror upb/remove-werror

    git checkout staging
    git rebase add-posix-lib-dependency
    git rebase remove-werror
}

setup()
{
    mkdir -p "$top"
    mkdir -p "$libs"
    mkdir -p "$apps"

    if test ! -d "$uk"; then
        git clone https://github.com/unikraft/unikraft "$uk"
        pushd "$uk" > /dev/null
        setup_unikraft
        popd > /dev/null
    fi

    if test ! -d "$libs"/musl; then
        git clone https://github.com/unikraft/lib-musl "$libs"/musl
        pushd "$libs"/musl > /dev/null
        setup_musl
        popd > /dev/null
    fi

    if test ! -d "$libs"/lwip; then
        git clone https://github.com/unikraft/lib-lwip "$libs"/lwip
        pushd "$libs"/lwip > /dev/null
        setup_lwip
        popd > /dev/null
    fi

    if test ! -d "$libs"/libcxx; then
        git clone https://github.com/unikraft/lib-libcxx "$libs"/libcxx
        pushd "$libs"/libcxx > /dev/null
        setup_libcxx
        popd > /dev/null
    fi

    if test ! -d "$libs"/libcxxabi; then
        git clone https://github.com/unikraft/lib-libcxxabi "$libs"/libcxxabi
        pushd "$libs"/libcxxabi > /dev/null
        setup_libcxxabi
        popd > /dev/null
    fi

    if test ! -d "$libs"/libunwind; then
        git clone https://github.com/unikraft/lib-libunwind "$libs"/libunwind
        pushd "$libs"/libunwind > /dev/null
        setup_libunwind
        popd > /dev/null
    fi

    if test ! -d "$libs"/compiler-rt; then
        git clone https://github.com/unikraft/lib-compiler-rt "$libs"/compiler-rt
        pushd "$libs"/compiler-rt > /dev/null
        setup_compiler_rt
        popd > /dev/null
    fi

    if test ! -d "$libs"/libc-test; then
        git clone https://github.com/unikraft/lib-libc-test "$libs"/libc-test
        pushd "$libs"/libc-test > /dev/null
        setup_libc_test
        popd > /dev/null
    fi

    if test ! -d "$libs"/libsodium; then
        git clone https://github.com/unikraft/lib-libsodium "$libs"/libsodium
        pushd "$libs"/libsodium > /dev/null
        setup_libsodium
        popd > /dev/null
    fi

    if test ! -d "$libs"/zlib; then
        git clone https://github.com/unikraft/lib-zlib "$libs"/zlib
        pushd "$libs"/zlib > /dev/null
        setup_zlib
        popd > /dev/null
    fi

    if test ! -d "$libs"/libuuid; then
        git clone https://github.com/unikraft/lib-libuuid "$libs"/libuuid
        pushd "$libs"/libuuid > /dev/null
        setup_libuuid
        popd > /dev/null
    fi

    if test ! -d "$libs"/python3; then
        git clone https://github.com/unikraft/lib-python3 "$libs"/python3
        pushd "$libs"/python3 > /dev/null
        setup_python3
        popd > /dev/null
    fi

    if test ! -d "$libs"/sqlite; then
        git clone https://github.com/unikraft/lib-sqlite "$libs"/sqlite
    fi

    if test ! -d "$libs"/redis; then
        git clone https://github.com/unikraft/lib-redis "$libs"/redis
    fi

    if test ! -d "$libs"/nginx; then
        git clone https://github.com/unikraft/lib-nginx "$libs"/nginx
        pushd "$libs"/nginx > /dev/null
        setup_nginx
        popd > /dev/null
    fi
}

build()
{
    pushd "$app" > /dev/null
    export UK_WORKDIR=$(pwd)/../../
    # Do not use LIBUKSIGNAL with Musl.
    kraft configure -n LIBUKSIGNAL -F -m x86_64 -p kvm
    kraft prepare
    kraft build -j $(nproc)
    popd > /dev/null
}

clean()
{
    pushd "$app" > /dev/null
    export UK_WORKDIR=$(pwd)/../../
    kraft clean -d
    git reset --hard HEAD
    popd > /dev/null
}

remove()
{
    rm -fr "$top"
}

_setup_networking()
{
    sudo ip link set dev virbr0 down
    sudo ip link del dev virbr0
    sudo ip link add virbr0 type bridge
    sudo ip address add 172.44.0.1/24 dev virbr0
    sudo ip link set dev virbr0 up
}
